Django/PythonTutorial/PythonTutorial/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^files/',include('files_upload.urls')),
    url(r'^forms/',include('forms.urls')),
    url(r'^views/',include('views.urls')),
    url(r'^users/',include('users.urls')),
    url(r'^mail/',include('mail.urls')),
    url(r'^translation/',include('translation.urls')),
    url(r'^serialization/',include('serialization.urls')),
]

Django/PythonTutorial/mail/urls.py
from django.conf.urls import url
from . import views

app_name = 'mail'

urlpatterns=[
    url(r'^$',views.IndexView.as_view(),name='compose'),
    url(r'^send/$',views.IndexView.as_view(),name='send'),
]

Django/PythonTutorial/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^register/$',views.register,name='register'),
    url(r'^change_password',views.change_password,name='change_password'),
    url(r'^login/$',views.user_login,name='login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^details/',views.details,name='details')
]

Django/PythonTutorial/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import BaseUserManager

# Create your models here.
class CustomUser(AbstractBaseUser):

    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    username = models.CharField(max_length=25)
    email_address = models.EmailField(unique=True)
    date_of_birth = models.DateField()
    profile_picture = models.ImageField()

    USERNAME_FIELD = 'email_address'
    EMAIL_FIELD = 'email_address'
    REQUIRED_FIELDS = [
        'first_name','last_name','username',
    ]
    is_active = True
    is_staff = False
    is_superuser = False


    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

    def get_short_name(self):
        return self.username

class CustomUserManager(BaseUserManager):
    def create_user(self,email_address,first_name,last_name,username,date_of_birth,profile_picture,password):
        new_user = CustomUser()
        new_user.first_name=first_name
        new_user.last_name=last_name
        new_user.set_password(password)
        new_user.username=username
        new_user.date_of_birth=date_of_birth
        new_user.profile_picture=profile_picture
        new_user.email_address=email_address
        new_user.save()
        return new_user

    def create_super_user(self,email_address,first_name,last_name,username,date_of_birth,profile_picture,password):
        new_user = CustomUser()
        new_user.first_name=first_name
        new_user.last_name=last_name
        new_user.set_password(password)
        new_user.username=username
        new_user.date_of_birth=date_of_birth
        new_user.profile_picture=profile_picture
        new_user.email_address=email_address
        new_user.is_superuser=True
        new_user.save()
        return new_user

Django/PythonTutorial/users/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User

class UserRegistrationForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email','username','password',]

class UserChangePasswordForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'username','password',
        ]

class UserLoginForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'username', 'password',
        ]

Django/PythonTutorial/users/views.py
from django.shortcuts import render,reverse
from django.contrib.auth.models import User
from .forms import UserRegistrationForm,UserChangePasswordForm,UserLoginForm
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request,'users/index.html')

def register(request):
    if request.method == 'POST':
        user_registration_form = UserRegistrationForm(request.POST)

        if user_registration_form.is_valid():
            # new_user = User.objects.create_user(
            #     username=request.POST['username'],
            #     email=request.POST['email'],
            #     password=request.POST['password'],
            #     first_name=request.POST['first_name'],
            #     last_name=request.POST['last_name'],
            # )
            # new_user.save()
            user_registration_form.save()
            request.session['successful_registration'] = True
            return HttpResponseRedirect(reverse('users:register'))

        return render(request, 'users/register.html', {
            'user_registration_form': user_registration_form,
            'has_registered': False,
        })

    # GET
    user_registration_form = UserRegistrationForm()
    has_registered = False
    try:
        has_registered = request.session['successful_registration']
        del request.session['successful_registration']
    except(KeyError):
        pass

    return render(request,'users/register.html',{
        'user_registration_form': user_registration_form,
        'has_registered': has_registered,
    })

def change_password(request):
    if request.method == "POST":
        user = User.objects.get(username=request.POST['username'])
        user.set_password(request.POST['password'])
        user.save()
        request.session['successful_password_change'] = True
        return HttpResponseRedirect(reverse('users:change_password'))

    change_password_form = UserChangePasswordForm()
    has_changed_password = False
    try:
        has_changed_password = request.session['successful_password_change']
        del request.session['successful_password_change']
    except(KeyError):
        pass
    return render(request,'users/change_password.html',{
        'change_password_form': change_password_form,
        'has_changed_password': has_changed_password,
    })

def user_login(request):
    if request.method == "POST":
        user = authenticate(request,
                            username=request.POST['username'],
                            password=request.POST['password']
                            )
        if user is not None:
            login(request,user)
            return HttpResponseRedirect(reverse('users:details'))
        else:
            login_form = UserLoginForm()
            return HttpResponse(render(request,'users/login.html',{
                'error_message': 'User <b>{}</b> does not exist.'.format(request.POST['username']),
                'login_form': login_form
            }))

    login_form = UserLoginForm()
    return render(request,'users/login.html',{
        'login_form': login_form,
    })

# @login_required(login_url='users:login')
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

def details(request):
    return render(request,'users/details.html')

Django/PythonTutorial/users/templates/users/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Change Password</title>
</head>
<body>
    {% if has_changed_password %}
        <div style="background: palegreen; color: seagreen;border: solid 2px seagreen;padding: 10px;">
            <p>Password has been successfully updated.</p>
        </div>
    {% endif %}
    <h2>Change Password Form</h2>
    <form method="POST" action="{% url 'users:change_password' %}">
        {% csrf_token %}
        {{ change_password_form.as_p }}
        <input type="submit" value="Change Password">
        <script type="text/javascript">
            document.getElementById('id_password').setAttribute('type','password');
        </script>
    </form>
</body>
</html>

Django/PythonTutorial/users/templates/users/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Details</title>
</head>
<body>
    {% if user.is_authenticated %}
        <div style="background: palegreen; color: seagreen;border: solid 2px seagreen;padding: 10px;">
            <p>Successful login.</p>
        </div>
        <h2>User Details:</h2>
        <hr>
        <ul>
            <li>First Name: {{ user.first_name }}</li>
            <li>Last Name: {{ user.last_name }}</li>
            <li>Email Address: {{ user.email }}</li>
            <li>Username: {{ user.username }}</li>
            <li>Password: {{ user.password }}</li>
        </ul>
        <hr>
        <p><a href="{% url 'users:logout' %}">Log Out</a></p>
    {% else %}
        <div style="background: indianred; color: darkred;border: solid 2px darkred;padding: 10px;">
            <p>You are not logged in. Log in to see your details.</p>
            <p><a href="{% url 'users:login' %}">Log in here</a></p>
        </div>
    {% endif %}
</body>
</html>

Django/PythonTutorial/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users Management</title>
</head>
<body>
    <h1>User management</h1>
    <ul>
        <li><a href="{% url 'users:register' %}">Add a new user.</a></li>
        <li><a href="{% url 'users:login' %}">Authenticate existing user.</a></li>
        <li><a href="{% url 'users:change_password' %}">Change user password.</a></li>
    </ul>
</body>
</html>

Django/PythonTutorial/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Login</title>
</head>
<body>
    {% if error_message %}
        <div style="background: indianred; color: darkred;border: solid 2px darkred;padding: 10px;">
            <p>{{ error_message }}</p>
            <p>
                <a href="{% url 'users:login' %}">Log in here</a>&nbsp; or
                <a href="{% url 'users:register' %}">Register a new user here.</a>
            </p>
        </div>
    {% endif %}
    <h2>User Login</h2>
    <form method="POST" action="{% url 'users:login' %}">
        {% csrf_token %}
        {{ login_form.as_p }}
        <input type="submit" value="Log In">
        <script type="text/javascript">
            document.getElementById('id_password').setAttribute('type','password');
        </script>
    </form>
</body>
</html>

Django/PythonTutorial/users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User registration</title>
</head>
<body>
    {% if has_registered %}
        <div style="background: palegreen; color: seagreen;border: solid 2px seagreen;padding: 10px;">
            <p>User {{ user.username }} has been registered.</p>
        </div>
    {% endif %}
    <h2>User Registration Form</h2>
    <form method="POST" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ user_registration_form.as_p }}
        <input type="submit" value="Register">
        <script type="text/javascript">
            document.getElementById('id_password').setAttribute('type','password');
        </script>
    </form>
</body>
</html>