Django/PythonTutorial/PythonTutorial/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^files/',include('files_upload.urls')),
    url(r'^forms/',include('forms.urls')),
    url(r'^views/',include('views.urls')),
    url(r'^users/',include('users.urls')),
    url(r'^mail/',include('mail.urls')),
    url(r'^translation/',include('translation.urls')),
    url(r'^serialization/',include('serialization.urls')),
]

Django/PythonTutorial/mail/urls.py
from django.conf.urls import url
from . import views

app_name = 'mail'

urlpatterns=[
    url(r'^$',views.IndexView.as_view(),name='compose'),
    url(r'^send/$',views.IndexView.as_view(),name='send'),
]

Django/PythonTutorial/views/urls.py
from django.conf.urls import url
from . import views

app_name = 'views'

urlpatterns = [
    url(r'^publishers/$',views.PublisherList.as_view(),name='publishers'),
    url(r'^authors/create/$',views.AuthorCreate.as_view(),name='author_create'),
    url(r'^authors/(?P<pk>[0-9]+)/details$',views.AuthorDetail.as_view(),name='author_detail'),
    url(r'^authors/(?P<pk>[0-9]+)/update$',views.AuthorUpdate.as_view(),name='author_update'),
    url(r'^authors/(?P<pk>[0-9]+)/delete$',views.AuthorDelete.as_view(),name='author_delete'),
    url(r'^add_book/$',views.BookCreate.as_view(),name='add_book')
]

Django/PythonTutorial/views/templates/views/author_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author Delete</title>
</head>
<body>

</body>
</html>

Django/PythonTutorial/views/templates/views/author_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author Form</title>
</head>
<body>
    <form method="post" action="{% url 'views:author_create' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add">
    </form>
</body>
</html>

Django/PythonTutorial/views/templates/views/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if success_message %}
        <div style="padding: 10px;background: palegreen;color: seagreen;">
            <p>{{ success_message }}</p>
        </div>
    {% endif %}
    <form action="{% url 'views:add_book' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ book_form.as_p }}
        <input type="submit" value="Add Book">
    </form>
</body>
</html>

Django/PythonTutorial/views/templates/views/publisher_list.html
<h1>List of publishers: </h1>
<ul>
    {% for publisher in object_list %}
        <li>{{ publisher }}</li>
    {% endfor %}
</ul>