Django/django-polls/polls/urls.py
from django.conf.urls import url

from . import views

app_name='polls'

urlpatterns = [
    # polls/
    url(r'^$',views.IndexView.as_view(),name='index'),
    # polls/{id}/
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    # polls/{id}/results/
    url(r'^(?P<pk>[0-9]+)/results/$',views.ResultsView.as_view(),name='results'),
    # polls/{id}/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
]

Django/django-polls/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    # This is for admin Question List display
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

Django/django-polls/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from .models import Question,Choice
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.template import loader

# Create your views here.

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     #template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list':latest_question_list,
#     }
#     return render(request, 'polls/index.html', context)#Alternative: return HttpResponse(template.render(context,request))
#
# def detail(request,question_id):
#     # Long method
#     # try:
#     #     question=Question.objects.get(pk=question_id)
#     # except:
#     #     raise Http404("Question with id {} does not exist".format(question_id))
#
#     question = get_object_or_404(Question, pk=question_id)
#     context = {
#         'question': question,
#     }
#     # response = "You're looking at the results of question {}."
#     # return HttpResponse(response.format(question_id))
#     return render(request, 'polls/detail.html', context)
#
# def results(request, question_id):
#     question = get_object_or_404(Question,pk=question_id)
#     return render(request,'polls/results.html',context={
#         'question':question,
#     })
#     # return HttpResponse("You're looking at question {} results".format(question_id))

def vote(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except(KeyError,Choice.DoesNotExist):
        #Redisplay Voting Form
        return render(request,'polls/detail.html',context={
            'question':question,
            'error_message':"You did not select a choice.",
        })
    else:
        # Update choice votes data
        selected_choice.votes +=1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    #return HttpResponse("You're voting on question {}".format(question_id))

class IndexView(generic.ListView):

    # Default template name : <app_name>/<model_name>_list.html. has to be overridden
    template_name = 'polls/index.html'
    # Default context object name is <model_name>_list and is thus overridden
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """" Return the last 5 published questions """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):

    # Default template name : <app_name>/<model_name>_detail.html. has to be overridden
    template_name = 'polls/detail.html'
    model = Question

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

Django/django-polls/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{#<ul>#}
{#{% for choice in question.choice_set.all %}#}
{#    <li>{{ choice.choice_text }}</li>#}
{#{% endfor %}#}
{#</ul>#}

{% if error_message %}
    <p>
        <strong>{{ error_message }}</strong>
    </p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br/>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

Django/django-polls/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>
            <b>
                <a {# href="/polls/{{ question.id }}/" #}
                    href="{% url 'polls:detail' question.id %}"
                   target="_blank">{{ question.question_text }}</a>
            </b>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

Django/django-polls/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>